<%

require 'run_loop'

date = Time.now.strftime('%Y-%m-%d-%H%M-%S')

FileUtils.mkdir("./screenshots") unless File.exists?("./screenshots")
FileUtils.mkdir("./reports") unless File.exists?("./reports")

xamarin_dir = "#{ENV['HOME']}/.xamarin"

devices = {}

device_list = ['neptune', 'venus', 'earp', 'mars', 'saturn', 'pegasi', 'hat', 'erik', 'denis', 'uranus']

device_list.each do |device|
  dir = "#{xamarin_dir}/devices/#{device}"
  ip = IO.read("#{dir}/ip") if File.exists?("#{dir}/ip")
  udid = IO.read("#{dir}/udid") if File.exists?("#{dir}/udid")
  report = "./reports/#{device}/#{date}-#{device}.html"
  ss_path = "./reports/#{device}/screenshots/"
  ht = {:dir => dir,
        :ip => ip,
        :udid => udid,
        :report => report,
        :ss_path => ss_path}
  devices[device.to_sym] = ht

  FileUtils.mkdir("./reports/#{device}") unless File.exists?("./reports/#{device}")
  FileUtils.mkdir("./reports/#{device}/screenshots") unless File.exists?("./reports/#{device}/screenshots")
end

default_report = "./reports/calabash-#{date}.html"
ss_path = "./screenshots/"

xcode_tools = RunLoop::XCTools.new
sims = {}

xcode_version = xcode_tools.xcode_version
minor_version = xcode_version.minor

if xcode_version >= RunLoop::Version.new('6.0')
  sims[:ipad2]     = "iPad 2 (8.#{minor_version} Simulator)"
  sims[:ipad2_mid] = 'iPad 2 (7.1 Simulator)'

  sims[:air] =     "iPad Air (8.#{minor_version} Simulator)"
  sims[:air_mid] = 'iPad Air (7.1 Simulator)'

  sims[:ipad]     = "iPad Retina (8.#{minor_version} Simulator)"
  sims[:ipad_mid] = 'iPad Retina (7.1 Simulator)'

  sims[:iphone4s]     = "iPhone 4s (8.#{minor_version} Simulator)"
  sims[:iphone4s_mid] = 'iPhone 4s (7.1 Simulator)'

  sims[:iphone5s]     = "iPhone 5s (8.#{minor_version} Simulator)"
  sims[:iphone5s_mid] = 'iPhone 5s (7.1 Simulator)'

  sims[:iphone5]     = "iPhone 5 (8.#{minor_version} Simulator)"
  sims[:iphone5_mid] = 'iPhone 5 (7.1 Simulator)'

  sims[:phone6] = "iPhone 6 (8.#{minor_version} Simulator)"
  sims[:phone6plus] = "iPhone 6 Plus (8.#{minor_version} Simulator)"

  sims[:default]     = "iPhone 5s (8.#{minor_version} Simulator)"
else
  sims[:ipad2]     = 'iPad - Simulator - iOS 7.1'
  sims[:ipad2_mid] = 'iPad - Simulator - iOS 7.0'
  sims[:ipad2_min] = 'iPad - Simulator - iOS 6.1'

  sims[:air] =     'iPad Retina (64-bit) - Simulator - iOS 7.1'
  sims[:air_mid] = 'iPad Retina (64-bit) - Simulator - iOS 7.0'
  sims[:air_min] = 'iPad Retina (64-bit) - Simulator - iOS 7.0'

  sims[:ipad]     = 'iPad Retina - Simulator - iOS 7.1'
  sims[:ipad_mid] = 'iPad Retina - Simulator - iOS 7.0'
  sims[:ipad_min] = 'iPad Retina - Simulator - iOS 6.1'

  sims[:iphone4s]     = 'iPhone Retina (3.5-inch) - Simulator - iOS 7.1'
  sims[:iphone4s_mid] = 'iPhone Retina (3.5-inch) - Simulator - iOS 7.0'
  sims[:iphone4s_min] = 'iPhone Retina (3.5-inch) - Simulator - iOS 6.1'

  sims[:iphone5s]     = 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'
  sims[:iphone5s_mid] = 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.0'
  sims[:iphone5s_min] = 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.0'

  sims[:iphone5]     = 'iPhone Retina (4-inch) - Simulator - iOS 7.1'
  sims[:iphone5_mid] = 'iPhone Retina (4-inch) - Simulator - iOS 7.0'
  sims[:iphone5_min] = 'iPhone Retina (4-inch) - Simulator - iOS 6.1'

  sims[:phone6] = 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'
  sims[:phone6plus] = 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'

  sims[:default]     = 'iPhone Retina (4-inch) - Simulator - iOS 7.1'
end

if ENV["USER"] == "jenkins"
  formatter = "progress"
  keep_sim_open_after = "0"
else
  formatter = "Slowhandcuke::Formatter"
  keep_sim_open_after = "1"
end

%>

verbose: CALABASH_FULL_CONSOLE_OUTPUT=1 DEBUG=1
common: -f <%= formatter %>

ss_path: SCREENSHOT_PATH=<%= ss_path %>

html_report:  -f 'Calabash::Formatters::Html' -o <%= default_report %>
neptune_html: -f 'Calabash::Formatters::Html' -o <%= devices[:neptune][:report] %>
venus_html:   -f 'Calabash::Formatters::Html' -o <%= devices[:venus][:report] %>
earp_html:    -f 'Calabash::Formatters::Html' -o <%= devices[:earp][:report] %>
mars_html:    -f 'Calabash::Formatters::Html' -o <%= devices[:mars][:report] %>
saturn_html:  -f 'Calabash::Formatters::Html' -o <%= devices[:saturn][:report] %>
pegasi_html:  -f 'Calabash::Formatters::Html' -o <%= devices[:pegasi][:report] %>

neptune_ss: SCREENSHOT_PATH=<%= devices[:neptune][:ss_path] %>
venus_ss:   SCREENSHOT_PATH=<%= devices[:venus][:ss_path] %>
earp_ss:    SCREENSHOT_PATH=<%= devices[:earp][:ss_path] %>
mars_ss:    SCREENSHOT_PATH=<%= devices[:mars][:ss_path] %>
saturn_ss:  SCREENSHOT_PATH=<%= devices[:saturn][:ss_path] %>
pegasi_ss:  SCREENSHOT_PATH=<%= devices[:pegasi][:ss_path] %>

reset_btw:    RESET_BETWEEN_SCENARIOS=1

app:           APP=./CalSmoke-cal.app

simulator:     -p app -p common -p ss_path -p html_report --tags ~@device_only --tags ~@device
sim_launch:    -p simulator  NO_STOP=<%= keep_sim_open_after %>
sim_no_launch: -p simulator NO_LAUNCH=1

sim61_4in:         -p sim_launch DEVICE_TARGET='iPhone Retina (4-inch) - Simulator - iOS 6.1'
sim61_4in_nl:      -p sim_launch DEVICE_TARGET='iPhone Retina (4-inch) - Simulator - iOS 6.1'
sim61_ipad:        -p sim_launch DEVICE_TARGET='iPad - Simulator - iOS 6.1'
sim61_ipad_nl:     -p sim_no_launch DEVICE_TARGET='iPad - Simulator - iOS 6.1'
sim61_ipad_r:      -p sim_launch DEVICE_TARGET='iPad Retina - Simulator - iOS 6.1'
sim61_ipad_r_nl:   -p sim_no_launch DEVICE_TARGET='iPad Retina - Simulator - iOS 6.1'

simulators:         SIMULATORS="<%= sims %>"
ipad2:              -p sim_launch DEVICE_TARGET="<%= sims[:ipad2] %>"
ipad2_mid:          -p sim_launch DEVICE_TARGET="<%= sims[:ipad2_mid] %>"
ipad2_min:          -p sim_launch DEVICE_TARGET="<%= sims[:ipad2_min] %>"

air:                -p sim_launch DEVICE_TARGET="<%= sims[:air] %>"
air_mid:            -p sim_launch DEVICE_TARGET="<%= sims[:air_mid] %>"
air_min:            -p sim_launch DEVICE_TARGET="<%= sims[:air_min] %>"

ipad:               -p sim_launch DEVICE_TARGET="<%= sims[:ipad] %>"
ipad_mid:           -p sim_launch DEVICE_TARGET="<%= sims[:ipad_mid] %>"
ipad_min:           -p sim_launch DEVICE_TARGET="<%= sims[:ipad_min] %>"

iphone4s:           -p sim_launch DEVICE_TARGET="<%= sims[:iphone4s] %>"
iphone4s_mid:       -p sim_launch DEVICE_TARGET="<%= sims[:iphone4s_mid] %>"
iphone4s_min:       -p sim_launch DEVICE_TARGET="<%= sims[:iphone4s_min] %>"

iphone5:            -p sim_launch DEVICE_TARGET="<%= sims[:iphone5] %>"
iphone5_mid:        -p sim_launch DEVICE_TARGET="<%= sims[:iphone5_mid] %>"
iphone5_min:        -p sim_launch DEVICE_TARGET="<%= sims[:iphone5_min] %>"

iphone5s:           -p sim_launch DEVICE_TARGET="<%= sims[:iphone5s] %>"
iphone5s_mid:       -p sim_launch DEVICE_TARGET="<%= sims[:iphone5s_mid] %>"
iphone5s_min:       -p sim_launch DEVICE_TARGET="<%= sims[:iphone5s_min] %>"

iphone6:         -p sim_launch DEVICE_TARGET="<%= sims[:phone6] %>"
iphone6plus:     -p sim_launch DEVICE_TARGET="<%= sims[:phone6plus] %>"

default:            -p sim_launch DEVICE_TARGET="<%= sims[:default] %>"
no_uia:             -p common -p ss_path -p html_report -p no_launch -p sim61_4in

# required only for devices
bundle_id:    BUNDLE_ID=sh.calaba.CalSmoke-cal

device_common:  -p common -p bundle_id --tags ~@simulator --tags ~@simulator_only

neptune_common: DEVICE_TARGET=<%= devices[:neptune][:udid] %> DEVICE_ENDPOINT=<%= devices[:neptune][:ip] %> -p device_common  -p neptune_html -p neptune_ss

# cannot test email views without launching on iOS 6
neptune:           -p neptune_common
neptune_no_launch: -p neptune_common -p no_launch --tags ~@email

venus_common:   DEVICE_TARGET=<%= devices[:venus][:udid] %>   DEVICE_ENDPOINT=<%= devices[:venus][:ip] %> -p device_common
venus:          -p venus_common

earp_common:   DEVICE_TARGET=<%= devices[:earp][:udid] %> DEVICE_ENDPOINT=<%= devices[:earp][:ip] %> -p device_common  -p earp_html -p earp_ss
earp:          -p earp_common

mars_common:   DEVICE_TARGET=<%= devices[:mars][:udid] %> DEVICE_ENDPOINT=<%= devices[:mars][:ip] %> -p device_common  -p mars_html -p mars_ss
mars:          -p mars_common

saturn_common:   DEVICE_TARGET=<%= devices[:saturn][:udid] %> DEVICE_ENDPOINT=<%= devices[:saturn][:ip] %> -p device_common  -p saturn_html -p saturn_ss
saturn:          -p saturn_common

pegasi_common:   DEVICE_TARGET=<%= devices[:pegasi][:udid] %> DEVICE_ENDPOINT=<%= devices[:pegasi][:ip] %> -p device_common  -p pegasi_html -p pegasi_ss
pegasi:          -p pegasi_common

hatp:   DEVICE_TARGET=<%= devices[:hat][:udid] %> DEVICE_ENDPOINT=<%= devices[:hat][:ip] %> -p device_common
erik:   DEVICE_TARGET=<%= devices[:erik][:udid] %> DEVICE_ENDPOINT=<%= devices[:erik][:ip] %> -p device_common
denis: DEVICE_TARGET=<%= devices[:denis][:udid] %> DEVICE_ENDPOINT=<%= devices[:denis][:ip] %> -p device_common
uranus: DEVICE_TARGET=<%= devices[:uranus][:udid] %> DEVICE_ENDPOINT=<%= devices[:uranus][:ip] %> -p device_common
